---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-plex-credentials
  namespace: gateway-arr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homepage-plex-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        PLEX_TOKEN: "{{ .plex_token }}"
  data:
    - secretKey: plex_token
      remoteRef:
        key: plex-token
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-grafana-credentials
  namespace: gateway-arr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homepage-grafana-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        GRAFANA_USER: "{{ .username }}"
        GRAFANA_PASS: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: default-service-admin
        property: username
    - secretKey: password
      remoteRef:
        key: default-service-admin
        property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homepage-qbittorrent-credentials
  namespace: gateway-arr
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: homepage-qbittorrent-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        QBITTORRENT_USER: "{{ .username }}"
        QBITTORRENT_PASS: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: qbittorrent-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: qbittorrent-credentials
        property: password
