apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gateway-arr

resources:
  - namespace.yaml
  - crd.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - homepage-deployment.yaml
  - homepage-service.yaml

images:
  - name: gateway-arr
    newName: ghcr.io/thebranchdriftcatalyst/gateway-arr
    newTag: latest
  - name: ghcr.io/thebranchdriftcatalyst/gateway-arr-homepage
    newName: ghcr.io/thebranchdriftcatalyst/gateway-arr-homepage
    newTag: latest
